"""
constants.py - 遊戲常數設定
"""

# 畫面尺寸（遊戲邏輯座標，不含邊框）
SCREEN_WIDTH  = 50
SCREEN_HEIGHT = 24

# 遊戲物理
GRAVITY           = 0.35
MAX_FALL_SPEED    = 2.8
PLAYER_MOVE_SPEED = 2
PLAYER_HP_MAX     = 5

# 平台設定
PLATFORM_MIN_WIDTH       = 6
PLATFORM_MAX_WIDTH       = 14
PLATFORM_SPEED_INITIAL   = 0.013   # 每幀向上滾動量（約 1 格 / 5 秒 @15fps）
PLATFORM_SPEED_INCREMENT = 0.0015  # 難度提升加速量（更緩慢）
PLATFORM_SPEED_MAX       = 0.06    # 最大速度上限
PLATFORM_SPAWN_INTERVAL  = 5       # 每幾格生成一個平台
PLATFORM_MOVING_CHANCE   = 0.18
PLATFORM_CRUMBLE_CHANCE  = 0.12
PLATFORM_SPRING_CHANCE   = 0.10
PLATFORM_DAMAGE_CHANCE   = 0.13
PLATFORM_HEAL_CHANCE     = 0.10

# 平台類型
PLATFORM_NORMAL  = "normal"
PLATFORM_DAMAGE  = "damage"
PLATFORM_HEAL    = "heal"
PLATFORM_CRUMBLE = "crumble"
PLATFORM_SPRING  = "spring"
PLATFORM_MOVING  = "moving"

# 遊戲元素字元
CHAR_PLAYER           = "@"
CHAR_PLATFORM_NORMAL  = "="
CHAR_PLATFORM_DAMAGE  = "#"
CHAR_PLATFORM_HEAL    = "+"
CHAR_PLATFORM_CRUMBLE = "~"
CHAR_PLATFORM_SPRING  = "^"
CHAR_PLATFORM_MOVING  = "-"
CHAR_EMPTY            = " "

# 邊框字元（雙線方框）
CHAR_BORDER_TL = "\u2554"   # ╔
CHAR_BORDER_TR = "\u2557"   # ╗
CHAR_BORDER_BL = "\u255a"   # ╚
CHAR_BORDER_BR = "\u255d"   # ╝
CHAR_BORDER_H  = "\u2550"   # ═
CHAR_BORDER_V  = "\u2551"   # ║
CHAR_BORDER_ML = "\u2560"   # ╠
CHAR_BORDER_MR = "\u2563"   # ╣

# 遊戲狀態
STATE_MENU     = "menu"
STATE_PLAYING  = "playing"
STATE_PAUSED   = "paused"
STATE_GAMEOVER = "gameover"

# FPS / 時間
TARGET_FPS = 15

# 排行榜
LEADERBOARD_MAX  = 5
LEADERBOARD_FILE = "scores.json"

# 難度提升週期（幀數）—— 每 450 幀 (~30 秒) 提升一次
DIFFICULTY_INTERVAL = 450

# 粒子效果設定
PARTICLE_MAX         = 80
PARTICLE_LAND_COUNT  = 6
PARTICLE_DMG_COUNT   = 12
PARTICLE_HEAL_COUNT  = 8
PARTICLE_SPRING_COUNT = 10
PARTICLE_CRUMBLE_COUNT = 8

# 螢幕特效
SCREEN_SHAKE_FRAMES = 4
SCREEN_FLASH_FRAMES = 3

# 連擊系統
COMBO_TIMEOUT_FRAMES = 45  # ~3 秒內沒踩平台就重置
